### ISSUE TITLE
question about how certificates are handled

### ISSUE THREAD

**Issue by eelucio** [FREVA-CLINT/freva-deployment#120]
I have a question on how the certificates are transferred to the VMs and e.g. levante and working afterwards.

for what I understand in the deployment we need to add 3 certficate files:

```toml
[certificates]                                                                                                                                                                                                                                                                            
public_keyfile = "${CFD}/freva_instance.cer"                                                                                                                                                                                                                                                        
private_keyfile = "${CFD}/freva_instance.key"                                                                                                                                                                                                                                                       
chain_keyfile = "${CFD}/freva_instance.pem" 
```

- those will be transferred (back) to the **VM** that is hosting the **web service** here:
  ```
  /opt/freva/freva_instance/web_service/
  cacert.pem # == ${CFD}/freva_instance.pem
  server-cert.crt # == ${CFD}/freva_instance.cer
  server-key.key # ==${CFD}/freva_instance.key
  ```
  (the key, cer, and pem actually were generated with the VM that hosts the web service)

- but also to the **VM** that hosts the **db service** as `/opt/freva/freva_instance/vault_service/freva.crt` and `/opt/freva/freva_instance/vault_service/config/freva.crt` (where `freva.crt == ${CFD}/freva_instance.cer`) 

- and also to e.g. levante to `$root_dit/freva/freva_instance.crt`  (where `freva.crt == ${CFD}/freva_instance.cer`)


when preparing the deployment to a new VM I noticed that for example in the case of xces and regiklim we have a different crt file at levante than at the corresponding VMs and still the communication is running smoothly.

So, what is the purpose of putting the crt at e.g. levante? I cannot trace back



thanks in advance
